### PR TITLE
WIP: alternative approach to 'simple' renderers

### PR DESCRIPTION
**Pull request by glenjamin**
Here's another alternative to the way "simple" renderers are handled in #12 

Unsure if this is better or not, but if the `simple` function was exposed it would allow consumers to do this in their own renderers too.

(this will have a minor conflict with #13)

### CODE REVIEW

**Comment by rexxars** [comment]
I kind of feel like the whole "simple" thing is a hack, so I'd rather not expose this and have someone rely on it. I do appreciate the effort, though!

**Comment by glenjamin** [comment]
No problem, cheers for the work today! I've just integrated 4.0 with my project and it's vastly simplified my syntax highlighting code :)

**Comment by rexxars** [comment]
Sweet! Out of curiosity, which library are you using for syntax highlighting?

**Comment by glenjamin** [comment]
I'm using http://prismjs.com/ - I did have something working with highlight too.

Latest version:
https://github.com/glenjamin/devcards-js/commit/481acbc2615fdbf82dbd450bde0dea6bb68752f8

HighlightJS
https://github.com/glenjamin/devcards-js/commit/c16a756
But decided against it here: https://github.com/glenjamin/devcards-js/pull/22#issuecomment-175176039


The key warnings are all fixed too, thanks!

**Pull request closed without merging**
